[package]
edition = "2018"
name = "rslint_lsp"
version = "0.0.0"
authors = ["Darin Morrison <darinmorrison@users.noreply.github.com>"]
description = "A language server implementation for rslint."
license = "MIT"
repository = "https://github.com/RDambrosio016/RSLint"

[[bin]]
name = "rslint-lsp"
path = "src/bin/main.rs"

[features]
default = ["threaded"]
corpus = []
threaded = ["tokio/rt-threaded"]

[build-dependencies]
anyhow = "1.0"

[dependencies]
anyhow = "1.0"
clap = "2.33"
codespan-lsp = "0.10"
codespan-reporting = "0.9"
dashmap = "5.1"
env_logger = "0.7"
futures = "0.3"
itertools = "0.9"
log = "0.4"
rayon = "1.4.0"
rslint_core = { path = "../rslint_core", version = "0.1" }
rslint_parser = { path = "../rslint_parser", version = "0.2" }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["io-std", "macros"] }
tower-lsp = "=0.13.1"
